
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_CV(
	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,


	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,


	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// SW //////////
	input 		     [9:0]		SW,


	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);


	
//=======================================================
//  REG/WIRE declarations
//=======================================================

	logic [13:0] r_LPF_threshold;
	logic [13:0] r_distance;
	logic reset_n;
	
	logic rx			;			
	logic tx_data       ;        	
	logic tx_end_flag   ;  

	
	assign clk 		= CLOCK_50;
	assign reset_n 	= RESET_N;
	assign enc2 		= SW[0];
	assign r_LPF_threshold 		= 14'd20;
	assign r_distance 			= 14'd173;
	//assign buad_setting			=2'b00;
	logic [15:0] cnt_means;	
	logic enc;
	logic step_col;

//=======================================================
//  Structural coding
//=======================================================
	 encoder s1(
  .clk_50M(CLOCK_50),
  .rst(reset_n), 
  .enc(enc),
	.cnt_means(cnt_means),
	.step_col(step_col)
	);
	

	seven_segment seg3(
		.in				(cnt_means[15:12]), 
		.out				(HEX3)
	);
	
	seven_segment seg2(
		.in				(cnt_means[11:8]), 
		.out				(HEX2)
	); 
	
	seven_segment seg1(
		.in				(cnt_means[7:4]), 
		.out				(HEX1)
	);
	
	seven_segment seg0(
		.in				(cnt_means[3:0]), 
		.out				(HEX0)
	);
	

	

endmodule
	
