
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_CV(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

	logic outclk, tx_req, write_en, read_en, wrreq_neg, rdreq_neg, wrreq, rdreq;
	logic [7:0] address;
	logic [15:0] reg_file [255:0];
	logic [15:0] write_data, write_data_neg;
	logic [15:0] read_data, read_data_fifo;	
	logic sclr, almost_empty, empty, full, usedw;
	logic [7:0] q, data_neg;
	

//=======================================================
//  Structural coding
//=======================================================
	

	
	spi_rx spi_rx0(
	.clk				(outclk),
	.rst				(~RESET_N),
	.sclk				(GPIO_0[1]),
	.mosi				(GPIO_0[0]),
	.ssn				(GPIO_0[2]),
	.address			(address),
	.wrreq			(wrreq),
	.rdreq			(rdreq),
	.wrreq_neg		(wrreq_neg),  
	.rdreq_neg		(rdreq_neg),
	.data				(write_data),
	.read_data		(read_data),
	.read_en			(read_en),
	.write_en		(write_en),
	.tx_req			(tx_req)
);

	spi_tx spi_tx0(
		.clk			(outclk),
		.rst			(~RESET_N),
		.tx_req		(tx_req),
		.sclk			(GPIO_0[1]),
		.ssn			(GPIO_0[2]),
		.mosi			(GPIO_0[0]),
		.data			(read_data),
		.data_fifo	(read_data_fifo),
		.address		(address),
		.miso			(GPIO_0[3])
);
	
	FIFO0 FIFO01(
		.clock				(outclk),
		.data					(write_data),
		.rdreq				(rdreq_neg),
		.sclr					(~RESET_N),
		.wrreq				(wrreq_neg),
		.almost_empty		(almost_empty),
		.empty				(empty),
		.full					(full),
		.q						(read_data_fifo),
		.usedw				(usedw)
	);

	pll p1(
		.refclk		(CLOCK_50),   //  refclk.clk
		.rst			(~RESET_N),      //   reset.reset
		.outclk_0	(outclk), // outclk0.clk
		.locked  	()  //  locked.export
	);
	

endmodule

